version: '3.6'

services:

  api:
    image: arnaudnilens/api-ga:latest
    restart: always

    links:
    - 'db:database'

    environment:
      APP_PORT: 3000
      DB_PORT: 3306
      DB_HOST: database
      DB_USER: user
      DB_PASS: user1234
      MYSQL_DB: db

    ports:
    - '3000:3000'
    
    expose:
    - '3000'
