version: '3.6'

services:
  web:
    image: arnaudnilens/web-ga:latest
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    expose:
      - '80'
      - '443'
    environment:
      DEBUG: nodejs-docker-express:*
